# create_clock -period 5.000 -name clk_pin_p -waveform {0.000 2.500} [get_ports clk_pin_p]
set_output_delay -clock [get_clocks clk_pin_p] 1.000 [get_ports led_pins*]
set_output_delay -clock [get_clocks clk_pin_p] -min -0.500 [get_ports led_pins*]

set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[3]}]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[7]}]
set_property DRIVE 12 [get_ports {led_pins[4]}]
set_property DRIVE 12 [get_ports {led_pins[5]}]
set_property DRIVE 12 [get_ports {led_pins[6]}]
set_property DRIVE 12 [get_ports {led_pins[7]}]
set_property SLEW SLOW [get_ports {led_pins[4]}]
set_property SLEW SLOW [get_ports {led_pins[5]}]
set_property SLEW SLOW [get_ports {led_pins[6]}]
set_property SLEW SLOW [get_ports {led_pins[7]}]
set_property IOSTANDARD LVDS [get_ports clk_pin_p]

set_property PACKAGE_PIN E19 [get_ports clk_pin_p]
set_property PACKAGE_PIN E18 [get_ports clk_pin_n]
set_property PACKAGE_PIN AM39 [get_ports {led_pins[0]}]
set_property PACKAGE_PIN AN39 [get_ports {led_pins[1]}]
set_property PACKAGE_PIN AR37 [get_ports {led_pins[2]}]
set_property PACKAGE_PIN AT37 [get_ports {led_pins[3]}]
set_property PACKAGE_PIN AR35 [get_ports {led_pins[4]}]
set_property PACKAGE_PIN AP41 [get_ports {led_pins[5]}]
set_property PACKAGE_PIN AP42 [get_ports {led_pins[6]}]
set_property PACKAGE_PIN AU39 [get_ports {led_pins[7]}]

# set_property IOB TRUE [all_fanin -only_cells -startpoints_only -flat [all_outputs]]

set_property IOSTANDARD LVDCI_15 [get_ports rst_pin]
set_property PACKAGE_PIN AV40 [get_ports rst_pin]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]